version: "3.7"
services:
  otel:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    command: --config /config/collector-config.yml
    volumes:
        - .:/config
        - ~/.aws:/root/.aws
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
    ports:
        - '4317:4317'

  app:
    build: ../../SampleApp
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION=us-west-2
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
      - LISTEN_ADDRESS=0.0.0.0:8000
      - OTEL_EXPORTER_OTLP_INSECURE=True
      - OTEL_RESOURCE_ATTRIBUTES=service.name=aws-otel-integ-test
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel:4317
    ports:
      - '8000:8000'

  validator:
    image: public.ecr.aws/aws-otel-test/aws-otel-test-validator:alpha 
    command: ${VALIDATOR_COMMAND}
    depends_on:
      - otel
      - app
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION=us-west-2
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
